# Generated by Django 5.1.1 on 2024-10-07 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_product_size_orderitem_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='clothes', to='shop.category', verbose_name='Категория'),
        ),
    ]
