# Generated by Django 5.1.1 on 2024-10-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0005_alter_product_image_alter_profile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="Фото"
            ),
        ),
    ]
